language: python

python:
  - "3.4"

addons:
  postgresql: "9.4"

services:
    - postgresql

before_script:
  - psql -c 'create database postgres;' -U postgres

install: "pip install -r server-requirements.txt"

script: pytest test_1.py