language: python

python:
  - "3.4"

addons:
  postgresql: "9.4"

services:
    - postgresql

before_script:
  - psql -U postgres postgres < schema.sql

install: "pip install -r server-requirements.txt"

script: pytest test_1.py
